
package org.virtualbox_4_2.jaxws;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.6 in JDK 6 Generated
 * source version: 2.1
 * 
 */
@WebServiceClient(name = "vboxService", targetNamespace = "http://www.virtualbox.org/Service", wsdlLocation = "file:/home/vbox/tinderbox/4.2-sdk/out/linux.amd64/release/bin/sdk/bindings/webservice/vboxwebService.wsdl")
public class VboxService extends Service {

	private final static URL VBOXSERVICE_WSDL_LOCATION;
	private final static Logger logger = Logger.getLogger(org.virtualbox_4_2.jaxws.VboxService.class.getName());

	static {
		URL url = null;
		try {
			URL baseUrl;
			baseUrl = org.virtualbox_4_2.jaxws.VboxService.class.getResource(".");
			url = new URL(baseUrl,
					"file:/home/vbox/tinderbox/4.2-sdk/out/linux.amd64/release/bin/sdk/bindings/webservice/vboxwebService.wsdl");
		} catch (MalformedURLException e) {
			logger.warning(
					"Failed to create URL for the wsdl Location: 'file:/home/vbox/tinderbox/4.2-sdk/out/linux.amd64/release/bin/sdk/bindings/webservice/vboxwebService.wsdl', retrying as a local file");
			logger.warning(e.getMessage());
		}
		VBOXSERVICE_WSDL_LOCATION = url;
	}

	public VboxService(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public VboxService() {
		super(VBOXSERVICE_WSDL_LOCATION, new QName("http://www.virtualbox.org/Service", "vboxService"));
	}

	/**
	 * 
	 * @return returns VboxPortType
	 */
	@WebEndpoint(name = "vboxServicePort")
	public VboxPortType getVboxServicePort() {
		return super.getPort(new QName("http://www.virtualbox.org/Service", "vboxServicePort"), VboxPortType.class);
	}

	/**
	 * 
	 * @param features A list of {@link javax.xml.ws.WebServiceFeature} to configure
	 *                 on the proxy. Supported features not in the
	 *                 <code>features</code> parameter will have their default
	 *                 values.
	 * @return returns VboxPortType
	 */
	@WebEndpoint(name = "vboxServicePort")
	public VboxPortType getVboxServicePort(WebServiceFeature... features) {
		return super.getPort(new QName("http://www.virtualbox.org/Service", "vboxServicePort"), VboxPortType.class,
				features);
	}

}
